import type { Metadata } from 'next';
import MenuAdmin from '@/components/adminComponentes/MenuAdmin';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Mi Pefil',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isVendedor = session?.user?.rol_usuario === 'vendedor';

  if (!isVendedor) {
    // 🔥 Redirecciona si NO es Vendedor
    return <meta httpEquiv="refresh" content="0; url=/" />;
  }

  return (
    <div className="flex min-h-screen">
      <div className="flex-1">{children}</div>
    </div>
  );
}
