import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Lista de Usuarios Activos',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="">{children}</div>;
}
