import type { Metadata } from 'next';
import { auth } from '@/auth'; // 🔥 IMPORTANTE: Importar el auth()

export const metadata: Metadata = {
  title: 'Mi perfil',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';
export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isComprador = session?.user?.rol_usuario === 'comprador';

  if (!isComprador) {
    return <meta httpEquiv="refresh" content="0; url=/" />;
  }

  return <div>{children}</div>;
}
