import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Turnos',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return <div className="w-full flex flex-col items-center">{children}</div>;
  return <div className="flex-1 p-6">{children}</div>;
}
