import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Ingresa tu email",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic"; // fuerza renderizado dinámico (evita cache)

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <div>{children}</div>
      <Footer />
    </SessionProvider>
  );
}
