import type { Metadata } from 'next';
import MenuVendedor from '@/components/VendedorComponentes/NavBarVendedor';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Editar Productos',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';
export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isVendedor = session?.user?.rol_usuario === 'vendedor';

  if (!isVendedor) {
    return <meta httpEquiv="refresh" content="0; url=/" />;
  }

  return (
    <div className="">
      <MenuVendedor />
      <main className="flex-1 lg:ml-64 ">{children}</main>
    </div>
  );
}
