import type { Metadata } from 'next';
import MenuAdmin from '@/components/adminComponentes/MenuAdmin';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Bienvenido Administrador',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isAdmin = session?.user?.rol_usuario === 'admin';

  if (!isAdmin) {
    return <meta httpEquiv="refresh" content="0; url=/" />;
  }

  return (
    <div className="">
      <MenuAdmin />
      <main className="flex-1 lg:ml-64 ">{children}</main>
    </div>
  );
}
