import type { Metadata } from 'next';
import { auth } from '@/auth'; // 🔥 IMPORTANTE: Importar el auth()

export const metadata: Metadata = {
  title: 'Mi Pefil',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isAdmin = session?.user?.rol_usuario === 'admin';

  if (!isAdmin) {
    // 🔥 Redirecciona si NO es admin
    return <meta httpEquiv="refresh" content="0; url=/" />;
  }

  return (
    <div className="flex min-h-screen">
      <div className="flex-1">{children}</div>
    </div>
  );
}
