import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Editar usuario",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen">    
    {/* MenuAdministrador */}
      <div className="flex-1 p-6">
        {children}
      </div>
    </div>
  );
}
