import type { Metadata } from 'next';
import Footer from '@/components/footer';
import Menu from '@/components/NavBar';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth'; // Importa la función de autenticación
export const metadata: Metadata = {
  title: 'Registro Usuario',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  // return <div className="w-full flex flex-col items-center">{children}</div>;
  return (
    <div className="">
      <SessionProvider session={session}>
        <Menu />
        {children}
        <Footer />
      </SessionProvider>
    </div>
  );
}
