import type { Metadata } from 'next';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Mi perfil',
  description: 'Generated by create next app',
};

// 👇 Esta línea es CLAVE
export const dynamic = 'force-dynamic';

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isVendedor = session?.user?.rol_usuario === 'vendedor';

  if (!isVendedor) {
    // 🔥 Redirecciona si NO es admin
    return <meta httpEquiv="refresh" content="0; url=/" />;
  }
  return <div>{children}</div>;
}
