import type { Metadata } from 'next';
import { inter } from '@/app/fonts';
import { SessionProvider } from 'next-auth/react';
import Menu from '@/components/NavBar';
import Footer from '@/components/footer';
// import { SharedStateProvider } from '@/context/estadoCompartido';
import { auth } from '@/auth'; //sirve para traer los datos de la sesion cuando trabajo con server

export const metadata: Metadata = {
  title: 'Mecanica Guemes',
  description: 'Generated by create next app',
};
export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isAdmin = session?.user?.rol_usuario === 'admin';
  const isVendedor = session?.user.rol_usuario === 'vendedor';

  return (
    <div className={`min-h-screen flex flex-col ${inter.className}`}>
      <SessionProvider session={session}>
        {/* <SharedStateProvider> */}
        {!(isAdmin || isVendedor) && <Menu />}

        {/* El main crece para empujar al footer abajo */}
        <main className="flex-1">{children}</main>

        {!(isAdmin || isVendedor) && <Footer />}
        {/* </SharedStateProvider> */}
      </SessionProvider>
    </div>
  );
}
